# Generated by Django 2.2.5 on 2019-12-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imgage',
            field=models.TextField(default='img/ratsNYC.png', verbose_name='image path'),
            preserve_default=False,
        ),
    ]
