# Generated by Django 2.2.5 on 2019-12-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_imgage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imgage',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='test.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
