# Generated by Django 2.2.5 on 2019-12-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191216_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='projectPage',
            field=models.FileField(default='test.html', upload_to='html/'),
            preserve_default=False,
        ),
    ]
